const fs = require('fs');
const path = require('path');

const vijayawadaBusNetwork = `
1 | IBRAHIMPATNAM - PORANKI | IBRAHIMPATNAM - SWATHI - KUMMARI PALEM - KR MARKET – RAILWAY STN - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE - KAMAYYATHOPU - PORANKI
1G | GOLLAPUDI-KANKIPADU | KUMMARI PALEM – BHAVANI PURAM - RAILWAY STN - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE - KANUR – PORANKI – KANKIPADU
2 | KALESWARARAO MARKET - RAMAVARRAPADU | KR MARKET - TUMMALAPALLI KALKSHETRAM - BUS STAND - OLD BUS STAND- BUNGLAW - LENINE CENTER - BESENT ROAD - RAMANDIRAM-VIJAYATALKIES- KOTHAVANTENA - SITARAMPURAM- CHUTTUGUNTA- MARUTHINAGAR- SRR COLLEGE- ANJANEYA SWAMY TEMPLE - MACHAVARAM-PADAVALAREVU- GUNADALA CHURCH- GUNADALA - GUNADALA VANTHENA - ESI - POWER OFFICE - RING ROAD – RAMAVARAPADU
2K | KALESWARARAO MARKET - KANURU | KALESWARARAO MARKET - KANURU
3 | KABELA - GOVERNMENT PRESS | KABELA - GOVERNMENT PRESS
3D | MILK PROJECT-DEVI NAGAR | MILK PROJECT-DEVI NAGAR
5 | KABELA - AUTONAGAR | KABELA – KR MARKET- TUMMALAPALLI KALKSHETRAM - BUS STAND - OLD BUS STAND – NAKKAL ROAD – BESENT ROAD – PUSHPA HOTEL – RAMESH HOSPITAL – BENZ CIRCLE –PATAMATA – AUTONAGAR
5G | KALESWARARAO MARKET - AUTONAGAR | KR MARKET- TUMMALAPALLI KALKSHETRAM - BUS STAND - OLD BUS STAND – NAKKAL ROAD – BESENT ROAD – PUSHPA HOTEL – RAMESH HOSPITAL - GURUNANAK COLONY – AUTONAGAR
5 SG | RAILWAY STATION - AUTONAGAR | RAILWAY STATION - OLD BUS STAND – NAKKAL ROAD – BESENT ROAD – PUSHPA HOTEL – RAMESH HOSPITAL - GURUNANAK COLONY- AUTONAGAR
7A | KALESWARARAO MARKET - PEDDA PULI PAKA | KALESWARARAO MARKET - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE -  PEDDA PULI PAKA
7R | MILK PROJECT - YANAMALA KUDHURU | MILK PROJECT – KR MARKET- PNBS – OLD BUS STAND - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE –YANAMALA KUDURU
10 | RAILWAY STATION - PENAMALURU | RAILWAY STN - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE - KANUR – PORANKI - PENAMALURU
10 C | RAILWAY STATION - CHODAVARAM | RAILWAY STN - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE - KANUR – PORANKI - CHODAVARAM
11 | MILK PROJECT - AUTONAGAR (ELURU ROAD) | MILK PROJECT - KR MARKET - TUMMALAPALLI KALKSHETRAM - BUS STAND - OLD BUS STAND- BUNGLAW - LENINE CENTER - BESENT ROAD - RAMANDIRAM-VIJAYATALKIES- KOTHAVANTENA - SITARAMPURAM- CHUTTUGUNTA- MARUTHINAGAR- SRR COLLEGE- ANJANEYA SWAMY TEMPLE - MACHAVARAM-PADAVALAREVU- GUNADALA CHURCH- GUNADALA - GUNADALA VANTHENA - ESI - POWER OFFICE - RING ROAD – RAMAVARAPADU - RAMESH HOSPITAL – BENZ CIRCLE –PATAMATA – AUTONAGAR
11H | KABELA - AUTONAGAR (ELURU ROAD) | KABELA – KR MARKET- TUMMALAPALLI KALKSHETRAM - BUS STAND - OLD BUS STAND- BUNGLAW - LENINE CENTER - BESENT ROAD - RAMANDIRAM-VIJAYATALKIES- KOTHAVANTENA - SITARAMPURAM- CHUTTUGUNTA- MARUTHINAGAR- SRR COLLEGE- ANJANEYA SWAMY TEMPLE - MACHAVARAM-PADAVALAREVU- GUNADALA CHURCH- GUNADALA - GUNADALA VANTHENA - ESI - POWER OFFICE - RING ROAD – RAMAVARAPADU - RAMESH HOSPITAL – BENZ CIRCLE –PATAMATA – AUTONAGAR
14 S | WAGON WORKSHOP COLONY - MADHURA NAGAR | WAGON WORKSHOP COLONY - MADHURA NAGAR
14 E | ELAPROLU - SATYANARAYANAPURAM COLONY | ELAPROLU - SATYANARAYANAPURAM COLONY
16 M | VOMBAY COLONY - GUNADALA | VOMBAY COLONY - GUNADALA
16 R | KALESWARARAO MARKET - NEW RAJA RAJESWARI PET | KALESWARARAO MARKET - NEW RAJA RAJESWARI PET
20 | MADHURANAGAR - MANGALAGIRI | MADHURANAGAR - MANGALAGIRI
23 | KALESWARARAO MARKET - PENAMALURU | KR MARKET – PNBS - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE - KANUR – PORANKI – PENAMALURU
23 A | FOURMEN BUNGLOW - GANGURU | RAILWAY STN - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE - KANUR – PORANKI - GANGURU
23 K | KALESWARARAO MARKET - KESARANENI VARI PALEM | KR MARKET – PNBS - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE - KANUR – PORANKI – KESARANENI VARI PALEM
26 H | HB COLONY - AUTONAGAR | HB COLONY-KR MARKET– PNBS - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR
28 B | PANJA - PANJA (BUNDAR ROAD) | PANJA – RAILWAY STN – BUNGLOW – PWD GROUNDS – BENZ CIRCLE – RAMESH HOSPITAL – VINAYAK THEATRE – NTR HEALTH UNIV – RAMAVARAPADU RING – MARUTHI NAGAR – VIJAYA TALKIES –RAILWAY STN - PANJA
28 E | PANJA - PANJA (ELURU ROAD) | PANJA – RAILWAY STN – VIJAYA TALKIES – MARUTHI NAGAR – RAMAVARAPADU RING – VINAYAK THEATRE – RAMESH HOSPITAL – BENZ CIRCLE – PWD GROUNDS – RAILWAY STN - PANJA
29 | KALESWARARAO MARKET - AUTONAGAR | KALESWARARAO MARKET - AUTONAGAR
31 | MILK PROJECT - AUTONAGAR | MILK PROJECT - KR MARKET- PNBS – OLD BUS STAND - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR
31 A | MILK PROJECT - THADIGADAPA | MILK PROJECT - KR MARKET- PNBS – OLD BUS STAND - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA – AUTONAGAR – KAMAYYATHOPU   - TADIGADAPA
31 H | HB COLONY - AUTONAGAR | HB COLONY - KR MARKET- PNBS – OLD BUS STAND - BUNDAR ROAD - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR
41 V | VOMBAY COLONY - AUTONAGAR | VOMBAY COLONY - AUTONAGAR
47 H | RAILWAY STATION - CHINNA KAKANI | RAILWAY STATION -  PNBS – VARADHI – MANIPAL HOSPITAL – MANGALAGIRI -  CHINNA KAKANI
47 N | KALESWARARAO MARKET - NRI HOSPITAL (METRO) | KALESWARARAO MARKET– PNBS – VARADHI – MANIPAL HOSPITAL – MANGALAGIRI  - NRI HOSPITAL
47 V | RAILWAY STATION - MANGALAGIRI | RAILWAY STATION – PNBS – VARADHI – MANIPAL HOSPITAL - MANGALAGIRI
48 K | NSB NAGAR - AUTO NAGAR | NSB NAGAR - AUTO NAGAR
48 N | AUTONAGAR - NUNNA | AUTONAGAR – BANDAR ROAD -  NUNNA
48 V | AUTONAGAR - VOMBAY COLONY | AUTONAGAR –BANDAR ROAD -  VOMBAY COLONY
49 | KALESWARARAO MARKET - NUNNA | KALESWARARAO MARKET -  PNBS  - NUNNA
49 M | KALESWARARAO MARKET - MANAGALAPURAM | KALESWARARAO MARKET – MANAGALAPURAM
49 P | KALESWARARAO MARKET - KUNDA VARI KANDRIKA | KALESWARARAO MARKET- PNBS  - KUNDA VARI KANDRIKA
54 | RAILWAY STATION - AUTONAGAR | RAILWAY STN – VIJAYA TALKIES – MARUTHI NAGAR – RAMAVARAPADU RING – VINAYAK THEATRE – RAMESH HOSPITAL – BENZ CIRCLE – PATAMATA - AUTONAGAR
55 | KALESWARARAO MARKET - KANURU | KR MARKET – PNBS – PWD GROUNDS – BENZ CIRCLE – PATAMATA – AUTONAGAR TERMINAL – KAMAYYATHOPU - KANURU
55 S | RAILWAY STATION - KANURU | RAILWAY STN – PNBS - PWD GROUNDS – BENZ CIRCLE – PATAMATA – AUTONAGAR TERMINAL – KAMAYYATHOPU - KANURU
77 | KALESWARARAO MARKET - RAMAVARRAPADU | KALESWARARAO MARKET - PNBS – ELURU ROAD- RAMAVARRAPADU
77 S | RAILWAY STATION - RAMAVARAPPADU | RAILWAY STATION  - ELURU ROAD - RAMAVARAPPADU
79 E | WHOLESALE MARKET - NIDAMANURU | WHOLESALE MARKET – PNBS – ELURU ROAD - PORANKI
79 B | WHOLESALE MARKET - PORANKI | WHOLESALE MARKET - PNBS – BANDAR ROAD- PORANKI
112 A | KALESWARARAO MARKET - MUSTHABADH | KALESWARARAO MARKET – MUSTHABADH
116 | KALESWARARAO MARKET - GANNAVARAM | KR MARKET – RAMAVARAPAPU RING – NIDAMANURU – GANNAVARAM
116 K | KALESWARARAO MARKET - KG PADU | KR MARKET – RAILWAY STN – KG PADU
121 | RAILWAT STATION - VANUKURU / MADDHURU | RAILWAY STN - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE - KAMAYYATHOPU – PORANKI - MADDURU
122 | KALESWARARAO MARKET - VANUKURU / MADDHURU | KR MARKET – PNBS - IGMC STADIUM - BENZ CIRCLE - PATAMATA - AUTONAGAR GATE - KAMAYYATHOPU – PORANKI - MADDURU
123 | SHABADH - KANKIPADU | SHABADH – BENZ CIRCLE - KANKIPADU
140 | KALESWARARAO MARKET  - UPPULURU | KR MARKET – PNBS – BANDAR ROAD – VRSEC - UPPULURU
141 | KALESWARARAO MARKET - UPPULURU (VIA RAILWAY STATION) | KR MARKET – RAILWAY STN  – PNBS – BANDAR ROAD – VRSEC - UPPULURU
144 | KONDAPALLI - AUTONGAR | KONDAPALLI – PNBS – BANDAR ROAD – BENZ CIRCLE - AUTONAGAR
145 | KONDAPALLI - NIDAMANURU | KONDAPALLI – PNBS – ELURU ROAD – NIDAMANURU
150 | KONDAPALLI - KANKIPADU (METRO) | KONDAPALI – PNBS – BANDAR ROAD – BENZ CIRCLE – VRSEC – KANKIPADU
152 | RAILWAT STATION - KAVULURU | RAILWAY STN – KAVULURU
154 | KALESWARARAO MARKET - KANKIPADU (METRO) | KR MARKET – BANDAR ROAD – KANKIPADU
188 | KONDAPALLI - GANNAVARAM (METRO) | KONDAPALLI – ELURU ROAD – GANNAVARAM
201 C | KALESWARARAO MARKET - PEDDAOUTPALLI | KR MARKET – PNBS – PEDAOUTPALLI
201 T | KALESWARARAO MARKET - TELAPROLU | KR MARKET – PNBS - TELPROLU
201 0 | KALESWARARAO MARKET - ORUGALLA | KALESWARARAO MARKET - ORUGALLA
203 C | KALESWARARAO MARKET - PODDUTURU | KALESWARARAO MARKET - PODDUTURU
203 K | KALESWARARAO MARKET - KONDURU | KALESWARARAO MARKET - KONDURU
203 T | KALESWARARAO MARKET - TTENNERU | KALESWARARAO MARKET - TTENNERU
208 | KALESWARARAO MARKET - AGIRAPALLI | KALESWARARAO MARKET - AGIRAPALLI
209 | KALESWARARAO MARKET - VALLURU PALEM | KALESWARARAO MARKET – PNBS – BANDAR ROAD - VALLURU PALEM
209 A | KALESWARARAO MARKET - ROYYURU | KALESWARARAO MARKET - PNBS  - BANDAR ROAD - ROYYURU
209 T | KALESWARARAO MARKET - THOTLAVALLURU | KALESWARARAO MARKET - PNBS  - BANDAR ROAD -  THOTLAVALLURU
211 | KALESWARARAO MARKET - KOLLVENU | KALESWARARAO MARKET - PNBS  - BANDAR ROAD -  KOLLVENU
212 | KALESWARARAO MARKET - CHIKKAVARAM | KALESWARARAO MARKET - CHIKKAVARAM
212 P | KALESWARARAO MARKET - GANNAVARAM (VIA P PATNAM) | KALESWARARAO MARKET - GANNAVARAM (VIA P PATNAM)
212 S | KALESWARARAO MARKET - GANNAVARAM (VIA S.GUDEM) | KALESWARARAO MARKET - GANNAVARAM (VIA S.GUDEM)
212 M | KALESWARARAO MARKET - MUDIRAJU PALEM | KALESWARARAO MARKET - MUDIRAJU PALEM
215 S | RAILWAY STATION - NUTAKKI | RAILWAY STATION - NUTAKKI
218 M | BUSSTAND - MAILAVARAM | BUSSTAND - MAILAVARAM
220 | KALESWARARAO MARKET - TENNARU | KALESWARARAO MARKET - TENNARU
222 | KALESWARARAO MARKET - VUYYURU (METRO) | KALESWARARAO MARKET – PNBS – BANDAR ROAD - VUYYURU
223 M | KALESWARARAO MARKET - MANIKONDA | KALESWARARAO MARKET – PNBS – BANDAR ROAD - MANIKONDA
226 | BUSSTAND - CHIRAVURU | BUSSTAND - CHIRAVURU
239 | KALESWARARAO MARKET - KANASANEPALLI | KALESWARARAO MARKET - KANASANEPALLI
241 | KANKIPADU - GANNAVARAM | KANKIPADU - GANNAVARAM
248 | AGIRAPALLI - KANKIPADU (METRO) | AGIRAPALLI – BANDAR ROAD - KANKIPADU
250 V | KALESWARARAO MARKET - VEMANDA | KALESWARARAO MARKET – PNBS – BANDAR ROAD – PORANKI - VEMANDA
252 | KALESWARARAO MARKET - HANUMAN JUNCTION (ELURU ROAD) | KALESWARARAO MARKET – PNBS – RAMAVARAPADU RING – GANNAVARAM - HANUMAN JUNCTION
252 B | KALESWARARAO MARKET - HANUMAN JUNCTION (BUNDAR ROAD) | KR MARKET – PNBS – BANDAR ROAD – BENZ CIRCLE – RAMAVARAPADU RING – GANNAVARAM – HANUMAN JUNCTION
257 | RAILWAY STATION - PEDDA OGIRALA | RAILWAY STN – PWD GROUND – BANDAR ROAD – PEDA OGIRALA
266 | VIJAYAWADA - KANCHIKA CHARLA (METRO) | VIJAYAWADA - KANCHIKA CHARLA
305 M | VIJAYAWADA - MOGHULURU -VEERULAPADU | VIJAYAWADA - MOGHULURU -VEERULAPADU
308 | VIJAYAWADA - NUZIVIDU (METRO) | VIJAYAWADA – NUNNA – CHINOUTPALLI- NUZIVIDU
309 | IBRAHIMPATAM - VIJAYAWADA - JAMALAPURAM | IBRAHIMPATAM - VIJAYAWADA - JAMALAPURAM
309 R | IBRAHIMPATAM - KANCHIKACHARLA - JAMALAPURAM - MILAVARAM - VIJAYAWADA | IBRAHIMPATAM - KANCHIKACHARLA - JAMALAPURAM - MILAVARAM - VIJAYAWADA
333 | KALESWARARAO MARKET - PAMARRU (METRO) | KALESWARARAO MARKET - PAMARRU
350 | VIJAYAWADA - MILAVARAM (METRO) | VIJAYAWADA - MILAVARAM
99 | RAILWAY STN – KANKIPADU (METRO) | RAILWAY STN – SATYANARANA PURAM – BRTS ROAD – RAMAVARAPADU RING – BENZ CIRCLE – PORANKI - KANKIPADU
`;

const knownCoordinates = {
  'RAILWAY STN': { lat: 16.5189, lng: 80.6232 },
  'RAILWAY STATION': { lat: 16.5189, lng: 80.6232 },
  'BENZ CIRCLE': { lat: 16.4979, lng: 80.6537 },
  'PATAMATA': { lat: 16.4951, lng: 80.6611 },
  'AUTONAGAR': { lat: 16.4907, lng: 80.6709 },
  'AUTONAGAR GATE': { lat: 16.4895, lng: 80.6695 },
  'AUTONAGAR TERMINAL': { lat: 16.4901, lng: 80.6715 },
  'BUNDAR ROAD': { lat: 16.5080, lng: 80.6400 },
  'BANDAR ROAD': { lat: 16.5080, lng: 80.6400 },
  'IGMC STADIUM': { lat: 16.5075, lng: 80.6430 },
  'KR MARKET': { lat: 16.5205, lng: 80.6135 },
  'KALESWARARAO MARKET': { lat: 16.5205, lng: 80.6135 },
  'PNBS': { lat: 16.5195, lng: 80.6180 },
  'BUS STAND': { lat: 16.5190, lng: 80.6170 },
  'OLD BUS STAND': { lat: 16.5170, lng: 80.6200 },
  'PUSHPA HOTEL': { lat: 16.5005, lng: 80.6465 },
  'RAMESH HOSPITAL': { lat: 16.5040, lng: 80.6520 },
  'KAMAYYATHOPU': { lat: 16.4839, lng: 80.6862 },
  'KANUR': { lat: 16.4740, lng: 80.6950 },
  'KANURU': { lat: 16.4740, lng: 80.6950 },
  'PORANKI': { lat: 16.4761, lng: 80.7068 },
  'PENAMALURU': { lat: 16.4680, lng: 80.7330 },
  'GANGURU': { lat: 16.4675, lng: 80.7279 },
  'MILK PROJECT': { lat: 16.5280, lng: 80.6080 },
  'TUMMALAPALLI KALKSHETRAM': { lat: 16.5220, lng: 80.6150 },
  'BUNGLAW': { lat: 16.5155, lng: 80.6250 },
  'LENINE CENTER': { lat: 16.5135, lng: 80.6280 },
  'BESENT ROAD': { lat: 16.5100, lng: 80.6330 },
  'RAMANDIRAM': { lat: 16.5160, lng: 80.6350 },
  'VIJAYATALKIES': { lat: 16.5175, lng: 80.6380 },
  'KOTHAVANTENA': { lat: 16.5190, lng: 80.6410 },
  'SITARAMPURAM': { lat: 16.5195, lng: 80.6440 },
  'CHUTTUGUNTA': { lat: 16.5180, lng: 80.6465 },
  'MARUTHINAGAR': { lat: 16.5205, lng: 80.6480 },
  'SRR COLLEGE': { lat: 16.5185, lng: 80.6489 },
  'ANJANEYA SWAMY TEMPLE': { lat: 16.5170, lng: 80.6510 },
  'MACHAVARAM': { lat: 16.5150, lng: 80.6540 },
  'PADAVALAREVU': { lat: 16.5130, lng: 80.6570 },
  'GUNADALA CHURCH': { lat: 16.5110, lng: 80.6600 },
  'GUNADALA': { lat: 16.5095, lng: 80.6620 },
  'GUNADALA VANTHENA': { lat: 16.5070, lng: 80.6650 },
  'ESI': { lat: 16.5045, lng: 80.6680 },
  'POWER OFFICE': { lat: 16.5015, lng: 80.6710 },
  'RING ROAD': { lat: 16.4985, lng: 80.6740 },
  'RAMAVARAPADU': { lat: 16.5241, lng: 80.6767 },
  'RAMAVARAPADU RING': { lat: 16.5241, lng: 80.6767 },
  'RAMAVARRAPADU': { lat: 16.5241, lng: 80.6767 },
  'NAKKAL ROAD': { lat: 16.5140, lng: 80.6270 },
  'PWD GROUNDS': { lat: 16.5120, lng: 80.6370 },
  'VINAYAK THEATRE': { lat: 16.5080, lng: 80.6540 },
  'GURUNANAK COLONY': { lat: 16.4930, lng: 80.6650 },
  'HB COLONY': { lat: 16.5320, lng: 80.6050 },
  'KABELA': { lat: 16.5090, lng: 80.5910 },
  'GOVERNMENT PRESS': { lat: 16.5150, lng: 80.5970 },
  'DEVI NAGAR': { lat: 16.5310, lng: 80.6010 },
  'PANJA': { lat: 16.5110, lng: 80.6190 },
  'NTR HEALTH UNIV': { lat: 16.5156, lng: 80.6699 },
  'MADHURANAGAR': { lat: 16.4970, lng: 80.6310 },
  'MANGALAGIRI': { lat: 16.4309, lng: 80.5804 },
  'VARADHI': { lat: 16.5022, lng: 80.6333 },
  'MANIPAL HOSPITAL': { lat: 16.4841, lng: 80.6192 },
  'CHINNA KAKANI': { lat: 16.4000, lng: 80.5600 },
  'NRI HOSPITAL': { lat: 16.4200, lng: 80.5750 },
  'WAGON WORKSHOP COLONY': { lat: 16.5750, lng: 80.6100 },
  'MADHURA NAGAR': { lat: 16.4980, lng: 80.6250 },
  'ELAPROLU': { lat: 16.5700, lng: 80.5900 },
  'SATYANARAYANAPURAM COLONY': { lat: 16.5213, lng: 80.6287 },
  'VOMBAY COLONY': { lat: 16.4980, lng: 80.6410 },
  'NSB NAGAR': { lat: 16.4850, lng: 80.6550 },
  'NUNNA': { lat: 16.5950, lng: 80.6950 },
  'MANAGALAPURAM': { lat: 16.5100, lng: 80.7100 },
  'KUNDA VARI KANDRIKA': { lat: 16.5050, lng: 80.7200 },
  'PEDDA PULI PAKA': { lat: 16.4780, lng: 80.6950 },
  'YANAMALA KUDURU': { lat: 16.4850, lng: 80.7000 },
  'CHODAVARAM': { lat: 16.4550, lng: 80.7450 },
  'KESARANENI VARI PALEM': { lat: 16.4600, lng: 80.7400 },
  'SWATHI': { lat: 16.5280, lng: 80.5950 },
  'KUMMARI PALEM': { lat: 16.5260, lng: 80.5900 },
  'IBRAHIMPATNAM': { lat: 16.5850, lng: 80.5550 },
  'GOLLAPUDI': { lat: 16.5300, lng: 80.5800 },
  'KANKIPADU': { lat: 16.4700, lng: 80.7100 },
  'BHAVANI PURAM': { lat: 16.5230, lng: 80.5950 },
  'FOURMEN BUNGLOW': { lat: 16.5180, lng: 80.6240 },
  'SHABADH': { lat: 16.5080, lng: 80.6680 },
  'KONDAPALLI': { lat: 16.6200, lng: 80.5300 },
  'NIDAMANURU': { lat: 16.5106, lng: 80.7164 },
  'WHOLESALE MARKET': { lat: 16.5210, lng: 80.6120 },
  'MUSTHABADH': { lat: 16.5450, lng: 80.5850 },
  'GANNAVARAM': { lat: 16.5400, lng: 80.8000 },
  'KG PADU': { lat: 16.5300, lng: 80.6300 },
  'VANUKURU': { lat: 16.4400, lng: 80.7300 },
  'MADDHURU': { lat: 16.4400, lng: 80.7300 },
  'MADDURU': { lat: 16.4400, lng: 80.7300 },
  'UPPULURU': { lat: 16.4870, lng: 80.6950 },
  'VRSEC': { lat: 16.4821, lng: 80.6914 },
  'KAVULURU': { lat: 16.5500, lng: 80.6000 },
  'PEDDAOUTPALLI': { lat: 16.5000, lng: 80.7400 },
  'TELAPROLU': { lat: 16.5150, lng: 80.7300 },
  'ORUGALLA': { lat: 16.5200, lng: 80.5900 },
  'PODDUTURU': { lat: 16.5100, lng: 80.7500 },
  'KONDURU': { lat: 16.5200, lng: 80.7600 },
  'TTENNERU': { lat: 16.5250, lng: 80.7700 },
  'AGIRAPALLI': { lat: 16.5300, lng: 80.7900 },
  'VALLURU PALEM': { lat: 16.4800, lng: 80.7400 },
  'ROYYURU': { lat: 16.4700, lng: 80.7500 },
  'THOTLAVALLURU': { lat: 16.3476, lng: 80.7795 },
  'KOLLVENU': { lat: 16.4600, lng: 80.7600 },
  'CHIKKAVARAM': { lat: 16.5300, lng: 80.8000 },
  'MUDIRAJU PALEM': { lat: 16.5200, lng: 80.7800 },
  'NUTAKKI': { lat: 16.5350, lng: 80.6200 },
  'MAILAVARAM': { lat: 16.5500, lng: 80.5800 },
  'TENNARU': { lat: 16.5100, lng: 80.6400 },
  'VUYYURU': { lat: 16.3651, lng: 80.8424 },
  'MANIKONDA': { lat: 16.4800, lng: 80.7500 },
  'CHIRAVURU': { lat: 16.5100, lng: 80.6500 },
  'KANASANEPALLI': { lat: 16.5000, lng: 80.7700 },
  'VEMANDA': { lat: 16.4400, lng: 80.7500 },
  'HANUMAN JUNCTION': { lat: 16.5550, lng: 80.8200 },
  'PEDDA OGIRALA': { lat: 16.3934, lng: 80.8142 },
  'PEDA OGIRALA': { lat: 16.3934, lng: 80.8142 },
  'VIJAYAWADA': { lat: 16.5062, lng: 80.6480 },
  'KANCHIKA CHARLA': { lat: 16.5400, lng: 80.5700 },
  'KANCHIKACHARLA': { lat: 16.5400, lng: 80.5700 },
  'MOGHULURU': { lat: 16.5000, lng: 80.6000 },
  'VEERULAPADU': { lat: 16.4900, lng: 80.6100 },
  'NUZIVIDU': { lat: 16.7850, lng: 80.8488 },
  'CHINOUTPALLI': { lat: 16.6500, lng: 80.7800 },
  'JAMALAPURAM': { lat: 16.5700, lng: 80.5500 },
  'MILAVARAM': { lat: 16.5400, lng: 80.5600 },
  'PAMARRU': { lat: 16.3230, lng: 80.9576 },
  'SATYANARANA PURAM': { lat: 16.5213, lng: 80.6287 },
  'BRTS ROAD': { lat: 16.5230, lng: 80.6600 },
  'ELURU ROAD': { lat: 16.5150, lng: 80.6700 },
  'TADIGADAPA': { lat: 16.4798, lng: 80.6979 },
  'BENZCIRCLE ELR BUS STOP': { lat: 16.4979, lng: 80.6537 },
  'EENADU BUS STOP-VJA': { lat: 16.4972, lng: 80.6560 },
  'GUDAVALLI CENTRE-VJA': { lat: 16.5120, lng: 80.7498 },
  'SIDDHARTHA ENG COLLEGE-VJA': { lat: 16.4821, lng: 80.6914 },
  'FIRE STATION BUS STOP-VJA': { lat: 16.5053, lng: 80.6285 },
  'KANAKADURGA WARADHI': { lat: 16.5022, lng: 80.6333 },
  'TADEPALLI X ROAD OPP DVR COMPLEX-CROMO ENTERPRISE': { lat: 16.4800, lng: 80.6183 },
  'MANGALAGIRI NIRMALA CONVENT BUS STOP': { lat: 16.4309, lng: 80.5804 },
  'ENIKEPADU     VJA': { lat: 16.5141, lng: 80.7062 },
  'VIJAYAWADA AIR PORT GATE': { lat: 16.5275, lng: 80.7857 },
  'PRASADAM PADU-VJA': { lat: 16.5203, lng: 80.6928 },
  'SRRCOLLEGEVJA': { lat: 16.5185, lng: 80.6489 },
  'SIDDHARTHA COLLEGE': { lat: 16.5058, lng: 80.6474 },
  'SWATHI THEATRE': { lat: 16.5263, lng: 80.5935 },
  'RAMAVARAPUPADU RING-VJA': { lat: 16.5241, lng: 80.6767 },
  'KAMAYYATHOPU CENTRE': { lat: 16.4839, lng: 80.6862 },
  'AUTO NAGAR BUS STATION': { lat: 16.4907, lng: 80.6709 },
};

let stopIdCounter = 100000;
const stopMap = new Map();
const allStops = [];
const allRoutes = [];
const allTrips = [];
const allStopTimes = [];
const allShapes = [];

function getOrCreateStop(name) {
  const key = name.trim().toUpperCase();
  if (stopMap.has(key)) return stopMap.get(key);
  const id = String(stopIdCounter++);
  const coords = knownCoordinates[name.trim()] || { lat: 16.5062 + Math.random() * 0.02, lng: 80.6480 + Math.random() * 0.02 };
  const stop = { id, name: name.trim(), lat: coords.lat, lng: coords.lng };
  stopMap.set(key, stop);
  allStops.push(stop);
  return stop;
}

function parseBusNetwork() {
  const lines = vijayawadaBusNetwork.trim().split('\n');
  let routeId = 1;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    const parts = trimmed.split('|').map(p => p.trim());
    if (parts.length < 3) continue;

    const busNumber = parts[0].trim();
    const routeName = parts[1].trim();
    const stopsStr = parts.slice(2).join(' | ').trim();
    const stopNames = stopsStr.split(/[–\-—]/).map(s => s.trim()).filter(Boolean);

    const routeIdStr = `VJA_${String(routeId).padStart(3, '0')}`;
    const tripId = `TRIP_${routeIdStr}`;
    const shapeId = `SHAPE_${routeIdStr}`;

    allRoutes.push({
      route_id: routeIdStr,
      agency_id: '1',
      route_short_name: busNumber,
      route_long_name: routeName,
      route_desc: '',
      route_type: '3',
      route_color: '38BDF8',
      route_text_color: 'FFFFFF',
    });

    allTrips.push({
      route_id: routeIdStr,
      service_id: 'ALL',
      trip_id: tripId,
      trip_headsign: routeName,
      direction_id: '0',
      shape_id: shapeId,
    });

    const shapePoints = [];

    stopNames.forEach((stopName, idx) => {
      const stop = getOrCreateStop(stopName);
      const arrivalH = 6 + Math.floor(idx / 10);
      const arrivalM = (idx * 3) % 60;
      const departureM = (arrivalM + 1) % 60;

      allStopTimes.push({
        trip_id: tripId,
        arrival_time: `${String(arrivalH).padStart(2, '0')}:${String(arrivalM).padStart(2, '0')}:00`,
        departure_time: `${String(arrivalH).padStart(2, '0')}:${String(departureM).padStart(2, '0')}:00`,
        stop_id: stop.id,
        stop_sequence: idx + 1,
      });

      const coords = knownCoordinates[stopName.trim()] || { lat: 16.5062 + Math.random() * 0.02, lng: 80.6480 + Math.random() * 0.02 };
      shapePoints.push({ lat: coords.lat, lng: coords.lng, seq: idx + 1 });
    });

    shapePoints.forEach((pt) => {
      allShapes.push({
        shape_id: shapeId,
        shape_pt_lat: pt.lat,
        shape_pt_lon: pt.lng,
        shape_pt_sequence: pt.seq,
      });
    });

    routeId++;
  }
}

parseBusNetwork();

const gtfsDir = path.join(__dirname, '..', '..', 'GTFS_Data');

function writeCSV(filename, headers, rows) {
  const headerLine = headers.join(',');
  const dataLines = rows.map(row => headers.map(h => {
    const val = row[h] !== undefined ? String(row[h]) : '';
    return val.includes(',') || val.includes('"') ? `"${val.replace(/"/g, '""')}"` : val;
  }).join(','));
  const content = [headerLine, ...dataLines].join('\n');
  fs.writeFileSync(path.join(gtfsDir, filename), content, 'utf8');
  console.log(`Written ${rows.length} rows to ${filename}`);
}

function normalizeName(n) {
  return n.replace(/\s+/g, ' ').trim();
}

const stopHeaders = ['stop_id', 'stop_code', 'stop_name', 'stop_desc', 'stop_lat', 'stop_lon', 'zone_id', 'stop_url', 'location_type', 'parent_station'];

writeCSV('stops_merged.txt', stopHeaders, allStops.map(s => ({
  stop_id: s.id,
  stop_code: s.id,
  stop_name: s.name,
  stop_desc: '',
  stop_lat: String(s.lat),
  stop_lon: String(s.lng),
  zone_id: '',
  stop_url: '',
  location_type: '0',
  parent_station: '',
})));

writeCSV('vja_routes.txt', ['route_id', 'agency_id', 'route_short_name', 'route_long_name', 'route_desc', 'route_type', 'route_color', 'route_text_color'], allRoutes);
writeCSV('vja_trips.txt', ['route_id', 'service_id', 'trip_id', 'trip_headsign', 'direction_id', 'shape_id'], allTrips);
writeCSV('vja_stop_times.txt', ['trip_id', 'arrival_time', 'departure_time', 'stop_id', 'stop_sequence'], allStopTimes);
writeCSV('vja_shapes.txt', ['shape_id', 'shape_pt_lat', 'shape_pt_lon', 'shape_pt_sequence'], allShapes);

console.log(`\nGTFS generation complete!`);
console.log(`Total routes: ${allRoutes.length}`);
console.log(`Total trips: ${allTrips.length}`);
console.log(`Total new stops: ${allStops.length}`);
console.log(`Total stops: ${allStops.length}`);
console.log(`Total stop_times: ${allStopTimes.length}`);
console.log(`Total shape points: ${allShapes.length}`);
